spring.application.name=kinal_code_quest

# Configuración de Conexión a MySQL con parámetros de compatibilidad
spring.datasource.url=jdbc:mysql://localhost:3306/kinal_code_quest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=IN5CM
spring.datasource.password=?donmoA5m@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto explícito para resolver el error de "Unable to determine Dialect"
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true