spring.application.name=kinal_code_in5cm
server.port=8082

# Configuracion de Conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/kinal_code_in5cm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=IN5CM
spring.datasource.password=?donmoA5m@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin